package com.unilib.dao;
// Generated May 23, 2017 2:26:40 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private Integer id;
	private String title;
	private String authors;
	private String isbn;
	private String publisher;
	private Date publisheddate;
	private String status;
	private Boolean inlib;
	private Integer rating;

	public Book() {
	}

	public Book(String title, String authors, String isbn, String publisher, Date publisheddate, String status, Boolean inlib, Integer rating) {
		this.title = title;
		this.authors = authors;
		this.isbn = isbn;
		this.publisher = publisher;
		this.publisheddate = publisheddate;
		this.status = status;
		this.inlib = inlib;
		this.setRating(rating);
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthors() {
		return this.authors;
	}

	public void setAuthors(String authors) {
		this.authors = authors;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public Date getPublisheddate() {
		return this.publisheddate;
	}

	public void setPublisheddate(Date publisheddate) {
		this.publisheddate = publisheddate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Boolean getInlib() {
		return this.inlib;
	}

	public void setInlib(Boolean inlib) {
		this.inlib = inlib;
	}

	public Integer getRating() {
		return rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

}
