package com.unilib.dao;
// Generated May 23, 2017 2:26:40 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer id;
	private String pin;
	private String name;

	public Student() {
	}

	public Student(String pin, String name) {
		this.pin = pin;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
